[providers.file]
  filename = "services.toml"
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":8443"

[certificatesResolvers.ctf.acme]
  email = "ambrose+ctf@makerforce.io"
  storage = "acme.json"
  keyType = "EC384"
  [certificatesResolvers.ctf.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
